# Generated by Django 4.2.2 on 2023-07-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Category',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
