# Generated by Django 4.2.2 on 2023-07-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.blogcomment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_0',
            field=models.TextField(blank=True, max_length=40000),
        ),
    ]
