# Generated by Django 4.2.2 on 2023-07-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_blogcomment_parent_alter_post_content_0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='head_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='head_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='head_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='head_4',
        ),
        migrations.AddField(
            model_name='post',
            name='ViewsCount',
            field=models.IntegerField(default=0),
        ),
    ]
